Выполнено задание MeetupView
js-tasks-ru/vue-20240924_user47113 pull request #3
Opened 2024-10-09 12:24 UTC by vajrock

2024-10-09 12:25 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-10 11:43 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-10 13:48 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-10 14:44 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-10 15:04 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-11 09:11 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-11 14:35 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-10-13 22:54 UTC, ShGKme requested changes
Требуется исправить потерю реактивности в `03-components/50-weather-components`, остальные задачи приняты

2024-10-13 22:54 UTC, ShGKme commented on 03-components/50-weather-components/WeatherApp.js
> +        <WeatherCard v-for="item in weatherData" :weatherItemData="item"/>
Стайл гайд рекомендует `kebab-case` для имён пропсов и событий в шаблоне: `weather-item-data`

2024-10-13 22:54 UTC, ShGKme commented on 03-components/50-weather-components/WeatherUIAlert.js
> +    const description = props.description
Здесь теряется реактивность. Получением компонентом нового пропса не приведёт к ререндерингу, так как он рендерит сохранённую при инициализации копию начального значения.

2024-10-13 22:54 UTC, ShGKme commented on 03-components/50-weather-components/WeatherUICard.js
> +    const item = props.weatherItemData
Аналогично

2024-10-13 22:54 UTC, ShGKme commented on 03-components/50-weather-components/WeatherUICardTitle.js
> +    const time = props.time
И здесь

2024-10-13 22:54 UTC, ShGKme commented on 03-components/50-weather-components/WeatherUIConditions.js
> +    const title = props.title
И здесь

2024-10-13 22:54 UTC, ShGKme commented on 03-components/50-weather-components/WeatherUIDetails.js
> +    const pressureInmmHg = getPressureInmmHg(props.pressure)
И здесь тоже

2024-10-13 22:54 UTC, ShGKme commented on 04-sfc/10-MeetupView-script-setup/MeetupAgenda.vue
> +  name: 'MeetupAgenda'
Компонентам в `script setup` обычно не дают дополнительно имя. Оно определяется компилятором по имени файла.

2024-10-14 06:57 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-14 07:01 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-14 18:12 UTC, ShGKme requested changes

2024-10-14 18:12 UTC, ShGKme commented on 03-components/50-weather-components/WeatherUIAlert.js
> +    const senderTpl = toRef(props.sender)
Это не корректное использование `toRef`. Его можно использовать в двух вариантах:
1. `toRef(obj, 'key')` для получения поля объекта
2. `toRef(() => obj.key)` для получения любого значения (более новый рекомендуемый вариант)

2024-10-14 18:12 UTC, ShGKme commented on 03-components/50-weather-components/WeatherUIAlert.js
> +    const senderTpl = toRef(props.sender)
https://vuejs.org/api/reactivity-utilities.html#toref

2024-10-15 12:00 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-15 12:01 UTC, vajrock commented
Сорри, что породил дополнительную проверку из-за своей невнимательности.

2024-10-20 20:00 UTC, ShGKme approved these changes

2024-10-20 20:00 UTC, ShGKme commented
> Сорри, что породил дополнительную проверку из-за своей невнимательности.

Ничего страшного, review - важная часть практики

2024-10-20 20:02 UTC, merged